environment-defaults:
  partying:
    branch: null
    repository: null
global:
  application_name: rubycon-team2
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Java 8 running
    on 64bit Amazon Linux/2.10.10
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
deploy:
  artifact: build/libs/rubycon-team2-0.0.1-SNAPSHOT.jar
