spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://ec2-13-209-26-139.ap-northeast-2.compute.amazonaws.com:3306/rubycon-partying-dev?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: catchup!@
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com:
      rubycon:
        rubyconteam2: debug
    root: info

