spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orm-test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: admin

  output:
    ansi:
      enabled: always

logging:
  level:
    root: info