# Elastic Beanstalk maps the internal port 5000 to the external port 80 to expose the application to the internet.
server:
  port: 5000
  forward-headers-strategy: native # for {baseUrl} apply 'https://'

spring:
  profiles:
    active: ${SPRING_ENV:prod}
    include: config

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # MySQL logging