spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:GOOGLE_CLIENT_ID_STRING}
            client-secret: ${GOOGLE_CLIENT_SECRET:GOOGLE_CLIENT_SECRET_STRING}
            scope: profile,email

custom:
  oauth2:
    kakao:
      client-id: ${KAKAO_CLIENT_ID:KAKAO_CLIENT_ID_STRING}
      client-secret: ${KAKAO_CLIENT_SECRET:KAKAO_CLIENT_SECRET_STRING}

app:
  jwt:
    tokenSecret: ${JWT_SECRET:JWT_SECRET_STRING}
    tokenExpirationMsec: 864000000