spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://ec2-3-35-17-62.ap-northeast-2.compute.amazonaws.com:3306/rubycon-partying-dev?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: habitbread!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

logging:
  level:
    com.rubycon.rubyconteam2: debug
    org.hibernate.SQL: debug
#    org.hibernate.type: trace